Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "limpar" is not found
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "cnuke" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "nuke" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "c" is not found
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
O bot está on
O bot está on
O bot está on
Ignoring exception in command exame:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await self.prepare(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 777, in prepare
    if not await self.can_run(ctx):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in can_run
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/utils.py", line 348, in async_all
    for elem in gen:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1087, in <genexpr>
    return await discord.utils.async_all(predicate(ctx) for predicate in predicates)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1646, in predicate
    raise MissingRole(item)
discord.ext.commands.errors.MissingRole: Role 839182749452992640 is required to run this command.
O bot está on
O bot está on
Traceback (most recent call last):
  File "Discordbot.py", line 516, in <module>
    bot.run(token.strip())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 566, in connect
    await self.ws.poll_event()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/gateway.py", line 582, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 4004
